"""Initial migration

Revision ID: 94fe07994309
Revises: 
Create Date: 2026-03-13 19:25:00.742106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94fe07994309'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('primary_muscle', sa.String(length=100), nullable=False),
    sa.Column('secondary_muscles', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('equipment', sa.String(length=100), nullable=True),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('instructions', sa.String(), nullable=True),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercises'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('total_xp', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('meal_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('target_calories', sa.Integer(), nullable=True),
    sa.Column('target_protein', sa.Integer(), nullable=True),
    sa.Column('target_carbs', sa.Integer(), nullable=True),
    sa.Column('target_fats', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_meal_plans_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meal_plans'))
    )
    op.create_table('meals_logged',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('food_name', sa.String(length=255), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('protein', sa.Integer(), nullable=True),
    sa.Column('carbs', sa.Integer(), nullable=True),
    sa.Column('fats', sa.Integer(), nullable=True),
    sa.Column('logged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_meals_logged_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meals_logged'))
    )
    op.create_table('recovery_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('fatigue_score', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recovery_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recovery_logs'))
    )
    op.create_table('workout_routines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workout_routines_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout_routines'))
    )
    op.create_table('workout_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('routine_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['routine_id'], ['workout_routines.id'], name=op.f('fk_workout_sessions_routine_id_workout_routines')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workout_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout_sessions'))
    )
    op.create_table('set_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rest_seconds', sa.Integer(), nullable=True),
    sa.Column('is_pr', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_set_logs_exercise_id_exercises')),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], name=op.f('fk_set_logs_session_id_workout_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_set_logs'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('set_logs')
    op.drop_table('workout_sessions')
    op.drop_table('workout_routines')
    op.drop_table('recovery_logs')
    op.drop_table('meals_logged')
    op.drop_table('meal_plans')
    op.drop_table('users')
    op.drop_table('exercises')
    # ### end Alembic commands ###
