"""Add Supabase Auth, Roles, CoachClients, and RoutineExercises

Revision ID: f4c02b700893
Revises: 94fe07994309
Create Date: 2026-03-16 18:14:28.637674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4c02b700893'
down_revision: Union[str, Sequence[str], None] = '94fe07994309'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('coach_clients',
    sa.Column('coach_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], name=op.f('fk_coach_clients_client_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], name=op.f('fk_coach_clients_coach_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('coach_id', 'client_id', name=op.f('pk_coach_clients'))
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('routine_exercises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('routine_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('target_sets', sa.Integer(), nullable=True),
    sa.Column('target_reps', sa.Integer(), nullable=True),
    sa.Column('target_weight_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_routine_exercises_exercise_id_exercises')),
    sa.ForeignKeyConstraint(['routine_id'], ['workout_routines.id'], name=op.f('fk_routine_exercises_routine_id_workout_routines'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routine_exercises'))
    )
    op.add_column('exercises', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('exercises', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.create_foreign_key(op.f('fk_exercises_created_by_users'), 'exercises', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('fk_meal_plans_user_id_users'), 'meal_plans', type_='foreignkey')
    op.create_foreign_key(op.f('fk_meal_plans_user_id_users'), 'meal_plans', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_meals_logged_user_id_users'), 'meals_logged', type_='foreignkey')
    op.create_foreign_key(op.f('fk_meals_logged_user_id_users'), 'meals_logged', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_recovery_logs_user_id_users'), 'recovery_logs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_recovery_logs_user_id_users'), 'recovery_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_set_logs_session_id_workout_sessions'), 'set_logs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_set_logs_session_id_workout_sessions'), 'set_logs', 'workout_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('profile_image_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.drop_column('users', 'email')
    op.add_column('workout_routines', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('fk_workout_routines_user_id_users'), 'workout_routines', type_='foreignkey')
    op.create_foreign_key(op.f('fk_workout_routines_user_id_users'), 'workout_routines', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_workout_sessions_routine_id_workout_routines'), 'workout_sessions', type_='foreignkey')
    op.drop_constraint(op.f('fk_workout_sessions_user_id_users'), 'workout_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_workout_sessions_routine_id_workout_routines'), 'workout_sessions', 'workout_routines', ['routine_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_workout_sessions_user_id_users'), 'workout_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_workout_sessions_user_id_users'), 'workout_sessions', type_='foreignkey')
    op.drop_constraint(op.f('fk_workout_sessions_routine_id_workout_routines'), 'workout_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_workout_sessions_user_id_users'), 'workout_sessions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_workout_sessions_routine_id_workout_routines'), 'workout_sessions', 'workout_routines', ['routine_id'], ['id'])
    op.drop_constraint(op.f('fk_workout_routines_user_id_users'), 'workout_routines', type_='foreignkey')
    op.create_foreign_key(op.f('fk_workout_routines_user_id_users'), 'workout_routines', 'users', ['user_id'], ['id'])
    op.drop_column('workout_routines', 'created_at')
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'address')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'profile_image_url')
    op.drop_constraint(op.f('fk_set_logs_session_id_workout_sessions'), 'set_logs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_set_logs_session_id_workout_sessions'), 'set_logs', 'workout_sessions', ['session_id'], ['id'])
    op.drop_constraint(op.f('fk_recovery_logs_user_id_users'), 'recovery_logs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_recovery_logs_user_id_users'), 'recovery_logs', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('fk_meals_logged_user_id_users'), 'meals_logged', type_='foreignkey')
    op.create_foreign_key(op.f('fk_meals_logged_user_id_users'), 'meals_logged', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('fk_meal_plans_user_id_users'), 'meal_plans', type_='foreignkey')
    op.create_foreign_key(op.f('fk_meal_plans_user_id_users'), 'meal_plans', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('fk_exercises_created_by_users'), 'exercises', type_='foreignkey')
    op.drop_column('exercises', 'is_public')
    op.drop_column('exercises', 'created_by')
    op.drop_table('routine_exercises')
    op.drop_table('user_roles')
    op.drop_table('coach_clients')
    op.drop_table('roles')
    # ### end Alembic commands ###
